#!/bin/python3

import math
import os
import random
import re
import sys

#
# Complete the 'insertionSort1' function below.
#
# The function accepts following parameters:
#  1. INTEGER n
#  2. INTEGER_ARRAY arr
#

def insertionSort1(n, arr): # 4 5 6 8 3
    # Write your code here
    key=arr[n-1]
    for i in range(n-2,-1,-1):
        if key <arr[i]:
            arr[i+1]=arr[i]
            print(' '.join(map(str, arr)))
            if i==0:
                arr[i]=key
                print(' '.join(map(str, arr)))
                break
               
                print(' '.join(map(str, arr)))
        else:
            arr[i+1]=key
            print(' '.join(map(str, arr)))
            break
            


if __name__ == '__main__':
    n = int(input().strip())

    arr = list(map(int, input().rstrip().split()))

    insertionSort1(n, arr)
